# Generated by Django 6.1 on 2026-08-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(choices=[('hot_flashes', 'Hot Flashes'), ('night_sweats', 'Night Sweats'), ('sleep', 'Sleep Problems'), ('mood', 'Mood Changes'), ('anxiety', 'Anxiety'), ('fatigue', 'Fatigue'), ('headache', 'Headache'), ('joint_pain', 'Joint/Muscle Discomfort'), ('brain_fog', 'Brain Fog'), ('vaginal_dryness', 'Vaginal Dryness'), ('urinary', 'Urinary Changes')], max_length=50)),
                ('severity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe')])),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
