# Generated by Django 6.1 on 2026-08-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomentry',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
