# Generated by Django 6.0.1 on 2026-08-23 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_symptomentry_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
