# Generated by Django 6.0.1 on 2026-08-23 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_symptomentry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('woman', 'Woman'), ('family', 'Family Member')], max_length=20, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('period_status', models.CharField(blank=True, max_length=50)),
                ('period_changes', models.JSONField(blank=True, default=list)),
                ('initial_symptoms', models.JSONField(blank=True, default=list)),
                ('menopause_stage', models.CharField(choices=[('premenopause', 'Premenopause'), ('perimenopause', 'Perimenopause'), ('postmenopause', 'Postmenopause'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
