# Generated by Django 6.0.1 on 2026-08-24 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_symptomentry_user_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('cancer_screening', 'Cancer Screening'), ('cervical_screening', 'Cervical Cancer Screening'), ('bone_health', 'Bone Health'), ('routine_check', 'Routine Health Check'), ('medication', 'Medication'), ('doctor', 'Doctor Appointment'), ('follow_up', 'Follow-up'), ('custom', 'Custom Reminder')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed', 'due_date', '-created_at'],
            },
        ),
    ]
