# Generated by Django 6.0.1 on 2026-08-29 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], max_length=20)),
                ('food_name', models.CharField(max_length=255)),
                ('portion', models.CharField(blank=True, max_length=100)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('calcium', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('health_benefits', models.JSONField(blank=True, default=list)),
                ('menopause_insight', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
