# Generated by Django 6.0.1 on 2026-08-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_mealentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealentry',
            old_name='menopause_insight',
            new_name='menopause_benefit',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='portion',
        ),
        migrations.AddField(
            model_name='mealentry',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='health_benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20),
        ),
    ]
