# Generated by Django 6.0.1 on 2026-08-30 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_rename_menopause_insight_mealentry_menopause_benefit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='menopause_insight',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='portion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='food_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='health_benefits',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='FamilyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('share_symptoms', models.BooleanField(default=False)),
                ('share_nutrition', models.BooleanField(default=False)),
                ('share_reminders', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_woman', to=settings.AUTH_USER_MODEL)),
                ('woman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
